In [3]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

In [26]:
t1 = torch.rand(3, 4, 5)
t1

tensor([[[0.3251, 0.9453, 0.6861, 0.4872, 0.2490],
         [0.8801, 0.5317, 0.9815, 0.7199, 0.7772],
         [0.5540, 0.4862, 0.6667, 0.9870, 0.9920],
         [0.3348, 0.9837, 0.6060, 0.3075, 0.8200]],

        [[0.0495, 0.0275, 0.1766, 0.2311, 0.4416],
         [0.0638, 0.4533, 0.3295, 0.5081, 0.1056],
         [0.7298, 0.0208, 0.1561, 0.0154, 0.6458],
         [0.2774, 0.1401, 0.7727, 0.5772, 0.9790]],

        [[0.5257, 0.5288, 0.6888, 0.4497, 0.7785],
         [0.9942, 0.9800, 0.2348, 0.2953, 0.3127],
         [0.9583, 0.0709, 0.2898, 0.3799, 0.8374],
         [0.9431, 0.6653, 0.6807, 0.4735, 0.0812]]])

In [3]:
# Выведите его форму (shape)

In [27]:
t1.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10

In [28]:
t2 = t1.reshape(6, 10)
t2

tensor([[0.3251, 0.9453, 0.6861, 0.4872, 0.2490, 0.8801, 0.5317, 0.9815, 0.7199,
         0.7772],
        [0.5540, 0.4862, 0.6667, 0.9870, 0.9920, 0.3348, 0.9837, 0.6060, 0.3075,
         0.8200],
        [0.0495, 0.0275, 0.1766, 0.2311, 0.4416, 0.0638, 0.4533, 0.3295, 0.5081,
         0.1056],
        [0.7298, 0.0208, 0.1561, 0.0154, 0.6458, 0.2774, 0.1401, 0.7727, 0.5772,
         0.9790],
        [0.5257, 0.5288, 0.6888, 0.4497, 0.7785, 0.9942, 0.9800, 0.2348, 0.2953,
         0.3127],
        [0.9583, 0.0709, 0.2898, 0.3799, 0.8374, 0.9431, 0.6653, 0.6807, 0.4735,
         0.0812]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [29]:
t1 * torch.Tensor([1, 4, 2, 2, 1])

tensor([[[0.3251, 3.7810, 1.3721, 0.9745, 0.2490],
         [0.8801, 2.1269, 1.9631, 1.4397, 0.7772],
         [0.5540, 1.9449, 1.3335, 1.9739, 0.9920],
         [0.3348, 3.9347, 1.2121, 0.6149, 0.8200]],

        [[0.0495, 0.1100, 0.3532, 0.4622, 0.4416],
         [0.0638, 1.8130, 0.6589, 1.0163, 0.1056],
         [0.7298, 0.0834, 0.3121, 0.0308, 0.6458],
         [0.2774, 0.5604, 1.5455, 1.1544, 0.9790]],

        [[0.5257, 2.1151, 1.3776, 0.8994, 0.7785],
         [0.9942, 3.9202, 0.4697, 0.5906, 0.3127],
         [0.9583, 0.2835, 0.5797, 0.7597, 0.8374],
         [0.9431, 2.6612, 1.3613, 0.9469, 0.0812]]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [46]:
t2.matmul(t2.T)

tensor([[4.9122, 4.0962, 1.4543, 2.7858, 3.6384, 3.2268],
        [4.0962, 5.1600, 1.7345, 2.8536, 4.0101, 3.5592],
        [1.4543, 1.7345, 0.8703, 1.0855, 1.3780, 1.3933],
        [2.7858, 2.8536, 1.0855, 2.9600, 2.0829, 2.5262],
        [3.6384, 4.0101, 1.3780, 2.0829, 4.0276, 3.4782],
        [3.2268, 3.5592, 1.3933, 2.5262, 3.4782, 3.8791]])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [73]:
x = torch.tensor(1.0, requires_grad = True)
z = torch.tensor(0.5, requires_grad = True)
t = torch.tensor(2.0, requires_grad = True)

y = x**3 + z - 75*t

y.backward()

print(x.grad, z.grad, t.grad)

tensor(3.) tensor(1.) tensor(-75.)


In [8]:
# Создайте единичный тензор размера 5x6

In [43]:
t = torch.ones(5, 6)
t

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [42]:
# Переведите его в формат numpy

In [44]:
t.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)